version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - db_network

  app:
    build: .
    command: gunicorn --env DJANGO_SETTINGS_MODULE=spacedb.settings_prod --access-logfile - --error-logfile - --capture-output --log-level info -b '0.0.0.0:8000' spacedb.wsgi
    volumes:
      - .:/app
      - static_volume:/app/static
      - /var/spacedb/raw:/app/data/rawdata
    ports:
      - 8000:8000
    networks:
      - nginx_network
      - db_network
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
    ports:
      - 80:80
    networks:
      - nginx_network
    depends_on:
      - app

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres_volume:
  static_volume:
