# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseApproach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_min', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='spaceobject',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='closeapproach',
            name='space_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceobjects.SpaceObject'),
        ),
    ]
