# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0002_auto_20181208_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
