# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0003_spaceobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='a',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='e',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='epoch',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='i',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='ma',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='om',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='w',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
