# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 01:59
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0004_auto_20181209_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='sbdb_entry',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
