# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0006_auto_20181214_2300'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spaceobject',
            index=models.Index(fields=['fullname'], name='spaceobject_fullnam_51b141_idx'),
        ),
    ]
