# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0007_auto_20181216_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='closeapproach',
            name='dist',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closeapproach',
            name='h_mag',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closeapproach',
            name='time_jd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closeapproach',
            name='v_rel',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
