# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0010_auto_20181217_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closeapproach',
            old_name='dist',
            new_name='dist_au',
        ),
        migrations.RenameField(
            model_name='closeapproach',
            old_name='dist_min',
            new_name='dist_min_au',
        ),
    ]
