# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0011_auto_20181217_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatsObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_dv', models.FloatField()),
                ('min_dv_duration', models.FloatField()),
                ('min_diameter', models.FloatField()),
                ('max_diameter', models.FloatField()),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceobjects.SpaceObject')),
            ],
        ),
    ]
