# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0013_nhatsobject_num_trajectories'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spaceobject',
            index=models.Index(fields=['slug'], name='spaceobject_slug_f1242a_idx'),
        ),
    ]
