# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0015_auto_20190105_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceobject',
            name='neo',
        ),
        migrations.RemoveField(
            model_name='spaceobject',
            name='pha',
        ),
    ]
