# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0017_auto_20190105_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbitClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('abbrev', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=500)),
                ('orbit_sentence', models.CharField(max_length=500)),
            ],
        ),
    ]
