# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0018_orbitclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceobject',
            name='orbit_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceobjects.OrbitClass'),
        ),
    ]
