# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0020_auto_20190105_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_path', models.CharField(max_length=200)),
                ('render_path', models.CharField(max_length=200)),
                ('spin_latitude', models.FloatField()),
                ('spin_longitude', models.FloatField()),
                ('spin_angle', models.FloatField()),
                ('period_hr', models.FloatField()),
                ('jd', models.FloatField()),
                ('yorp', models.FloatField()),
                ('equiv_diameter_km', models.FloatField()),
                ('quality', models.IntegerField()),
                ('space_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaceobjects.SpaceObject')),
            ],
        ),
    ]
