# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0021_shapemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='yorp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
