# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0022_auto_20190129_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='equiv_diameter_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
