# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0023_auto_20190129_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='quality',
            field=models.FloatField(),
        ),
    ]
