# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import spaceobjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0024_auto_20190129_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='object_type',
            field=models.CharField(choices=[(spaceobjects.models.ObjectType('ASTEROID'), 'ASTEROID'), (spaceobjects.models.ObjectType('COMET'), 'COMET')], default='ASTEROID', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='spaceobject',
            index=models.Index(fields=['orbit_class'], name='spaceobject_orbit_c_56d89c_idx'),
        ),
        migrations.AddIndex(
            model_name='spaceobject',
            index=models.Index(fields=['object_type'], name='spaceobject_object__a115d6_idx'),
        ),
    ]
