# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-24 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0026_auto_20190223_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='sbdb_order_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
