# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-24 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0027_spaceobject_sbdb_order_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spaceobject',
            index=models.Index(fields=['sbdb_order_id'], name='spaceobject_sbdb_or_ff8d91_idx'),
        ),
    ]
