# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-24 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0028_auto_20190224_1945'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spaceobject',
            name='spaceobject_sbdb_or_ff8d91_idx',
        ),
        migrations.RemoveField(
            model_name='spaceobject',
            name='sbdb_order_id',
        ),
    ]
