# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0029_auto_20190224_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbitclass',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spaceobject',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='orbit_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaceobjects.OrbitClass'),
        ),
    ]
