# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0032_auto_20190516_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='quality',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
