# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0033_auto_20190516_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapemodel',
            name='source',
            field=models.CharField(default='damit', max_length=512),
            preserve_default=False,
        ),
    ]
