# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-31 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0035_auto_20190707_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceobject',
            name='diameter_estimate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
