# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-08-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0036_spaceobject_diameter_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceobject',
            name='object_type',
            field=models.CharField(choices=[(b'ASTEROID', 'ASTEROID'), (b'COMET', 'COMET')], max_length=20),
        ),
    ]
