# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceobjects', '0037_auto_20190831_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceobject',
            name='spec_B',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='spec_T',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
